debug = True
auto_auth = True and debug
app_id = 112233 #fixme: should be generated by adding a app by developer
cookie_secret = "da39a3ee5e6b4b0d3255bfef95601890afd80709"

redis = {
    "host": "10.132.17.58",
    "port": 6379,
}
redis_conn_life = 60 * 2


SQL_HOST = "rds2uzmf32uzmf31367575249378.mysql.rds.aliyuncs.com"
SQL_USER = "liwei"
SQL_PASSWORD = "Jiahe804"

auth_db = {
    "driver": "MySQLdb",
    "host": SQL_HOST,
    "database": "account_db",
    "user": SQL_USER,
    "password": SQL_PASSWORD,
    "num_threads": 1,
    "tx_connection_pool_size": 1,
    "queue_timeout": 1,
    "thread_idle_life": 60*60,
}

wh_db = {
    "driver": "MySQLdb",
    "host": SQL_HOST,
    "database": "wh_db",
    "user": SQL_USER,
    "password": SQL_PASSWORD,
    "num_threads": 1,
    "tx_connection_pool_size": 1,
    "queue_timeout": 1,
    "thread_idle_life": 60*60,
}